name: Create Tag and release

on:
    push:
      # Sequence of patterns matched against refs/tags
      tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write
        repository-projects: write
    steps:
        - name: checkout code
          id: checkout_code
          uses: actions/checkout@v2
        - name: create release
          id: create_tag
          uses: actions/create-release@v1
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            body: |
                Changes in this Release
                - First Change
                - Second Change
            draft: false
            prerelease: false
        - name: Auto tag release
          id: auto_tag_release
          uses: Klemensas/action-autotag@stable
          with:
            tag_prefix: "v"
            version: ${{ github.ref }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
            