name: Create Tag

on: ['push', 'pull_request']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write
        repository-projects: write
    steps:
        - name: checkout code
          id: checkout_code
          uses: actions/checkout@v2
        - name: create release
          id: create_tag
          uses: actions/create-release@v1
        - name: Auto tag release
          id: auto_tag_release
          uses: Klemensas/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        tag_prefix: "v"
        version: "1.0.1.23"